-- Colleges
INSERT INTO colleges (college_id, college_name) VALUES
    (gen_random_uuid(), 'U Maryland: College Park'),
    (gen_random_uuid(), 'Columbia U'),
    (gen_random_uuid(), 'UC Berkeley'),
    (gen_random_uuid(), 'Cornell U'),
    (gen_random_uuid(), 'Georgia Tech'),
    (gen_random_uuid(), 'Harvard U'),
    (gen_random_uuid(), 'Northern Arizona U'),
    (gen_random_uuid(), 'Ohio State U'),
    (gen_random_uuid(), 'San Jose State U'),
    (gen_random_uuid(), 'Stanford U'),
    (gen_random_uuid(), 'UC Irvine'),
    (gen_random_uuid(), 'UC Los Angeles'),
    (gen_random_uuid(), 'U Houston'),
    (gen_random_uuid(), 'U Maryland: Baltimore County'),
    (gen_random_uuid(), 'U North Carolina'),
    (gen_random_uuid(), 'U Oregon'),
    (gen_random_uuid(), 'U Texas'),
    (gen_random_uuid(), 'U Virginia'),
    (gen_random_uuid(), 'U Washington'),
    (gen_random_uuid(), 'Virginia Tech'),
    (gen_random_uuid(), 'Yale U'),
    (gen_random_uuid(), 'Wellesley U'),
    (gen_random_uuid(), 'UC San Diego'),
    (gen_random_uuid(), 'UC Davis'),
    (gen_random_uuid(), 'U Southern California'),
    (gen_random_uuid(), 'Cal Poly Pomona'),
    (gen_random_uuid(), 'UC Merced'),
    (gen_random_uuid(), 'California State U, Fullerton'),
    (gen_random_uuid(), 'Palmer College of Chiropractic West'),
    (gen_random_uuid(), 'Santa Monica College'),
    (gen_random_uuid(), 'East Lost Angeles College'),
    (gen_random_uuid(), 'UC San Francisco'),
    (gen_random_uuid(), 'UC Santa Cruz'),
    (gen_random_uuid(), 'Pasadena City College'),
    (gen_random_uuid(), 'Portland Community College'),
    (gen_random_uuid(), 'UC Santa Barbara'),
    (gen_random_uuid(), 'U Pennsylvania'),
    (gen_random_uuid(), 'Berklee College of Music'),
    (gen_random_uuid(), 'U Maryland: Baltimore'),
    (gen_random_uuid(), 'Santa Rosa Junior College'),
    (gen_random_uuid(), 'Georgetown University'),
    (gen_random_uuid(), 'U Nebraska, Kearney'),
    (gen_random_uuid(), 'Pacific College of Oriental Medicine'),
    (gen_random_uuid(), 'UC Riverside'),
    (gen_random_uuid(), 'U Maryland: University College'),
    (gen_random_uuid(), 'California College of the Arts'),
    (gen_random_uuid(), 'Arizona State U'),
    (gen_random_uuid(), 'U Hawaii - Maui College'),
    (gen_random_uuid(), 'Leeward Community College'),
    (gen_random_uuid(), 'Kapi''olani Community College'),
    (gen_random_uuid(), 'U Hawaii - Manoa'),
    (gen_random_uuid(), 'U Hawaii - West Oahu'),
    (gen_random_uuid(), 'Carnegie Mellon U'),
    (gen_random_uuid(), 'U Pittsburgh'),
    (gen_random_uuid(), 'Virginia Commonwealth U'),
    (gen_random_uuid(), 'Point Park University'),
    (gen_random_uuid(), 'Massachusetts Institute of Technology'),
    (gen_random_uuid(), 'Bentley University'),
    (gen_random_uuid(), 'Rutgers U - New Brunswick'),
    (gen_random_uuid(), 'U Illinois Urbana-Champaign'),
    (gen_random_uuid(), 'Saint Peter''s University'),
    (gen_random_uuid(), 'College of Staten Island'),
    (gen_random_uuid(), 'Seattle Central College'),
    (gen_random_uuid(), 'San Francisco State U'),
    (gen_random_uuid(), 'Bastyr U'),
    (gen_random_uuid(), 'Central Washington U'),
    (gen_random_uuid(), 'San Diego Miramar College'),
    (gen_random_uuid(), 'California State U, Long Beach'),
    (gen_random_uuid(), 'SUNY Stony Brook '),
    (gen_random_uuid(), 'New York U'),
    (gen_random_uuid(), 'Maryland Institute College of Art'),
    (gen_random_uuid(), 'Cosumnes River College'),
    (gen_random_uuid(), 'West Coast University'),
    (gen_random_uuid(), 'U Oklahoma'),
    (gen_random_uuid(), 'Univ of Oklahoma'),
    (gen_random_uuid(), 'George Mason U'),
    (gen_random_uuid(), 'Chapman Univ'),
    (gen_random_uuid(), 'SUNY Empire State College'),
    (gen_random_uuid(), 'U Chicago'),
    (gen_random_uuid(), 'University of Alaska Southeast'),
    (gen_random_uuid(), 'Northeastern University'),
    (gen_random_uuid(), 'San Diego State University'),
    (gen_random_uuid(), 'Case Western Reserve University'),
    (gen_random_uuid(), 'Berkeley City College'),
    (gen_random_uuid(), 'New Jersey Institute of Technology'),
    (gen_random_uuid(), 'Boston University'),
    (gen_random_uuid(), 'The Juilliard School');

--Events
INSERT INTO events (event_code, event_name,	event_level, gender_category, is_nandu) VALUES 
    ('NFN111', 'Advanced Female Nandu Longfist', 'A', 'F', TRUE),
    ('NMN111', 'Advanced Male Nandu Longfist', 'A', 'M', TRUE),
    ('NFN112', 'Advanced Female Nandu Southern Fist', 'A', 'F', TRUE),
    ('NMN112', 'Advanced Male Nandu Southern Fist', 'A', 'M', TRUE),
    ('NFN311', 'Advanced Female Nandu Taiji Barehand', 'A', 'F', TRUE),
    ('NMN311', 'Advanced Male Nandu Taiji Barehand', 'A', 'M', TRUE),
    ('AFA101', 'Advanced Female Longfist', 'A', 'F', FALSE),
    ('AMA101', 'Advanced Male Longfist', 'A', 'M', FALSE),
    ('AFA102', 'Advanced Female Southern Fist', 'A', 'F', FALSE),
    ('AMA102', 'Advanced Male Southern Fist', 'A', 'M', FALSE),
    ('AFA121', 'Advanced Female Straightsword', 'A', 'F', FALSE),
    ('AMA121', 'Advanced Male Straightsword', 'A', 'M', FALSE),
    ('AFA122', 'Advanced Female Broadsword', 'A', 'F', FALSE),
    ('AMA122', 'Advanced Male Broadsword', 'A', 'M', FALSE),
    ('AFA123', 'Advanced Female Southern Broadsword', 'A', 'F', FALSE),
    ('AMA123', 'Advanced Male Southern Broadsword', 'A', 'M', FALSE),
    ('AFA141', 'Advanced Female Spear', 'A', 'F', FALSE),
    ('AMA141', 'Advanced Male Spear', 'A', 'M', FALSE),
    ('AFA142', 'Advanced Female Staff', 'A', 'F', FALSE),
    ('AMA142', 'Advanced Male Staff', 'A', 'M', FALSE),
    ('AFA143', 'Advanced Female Southern Staff', 'A', 'F', FALSE),
    ('AMA143', 'Advanced Male Southern Staff', 'A', 'M', FALSE),
    ('AMF201', 'Advanced Female Traditional Open Barehand', 'A', 'F', FALSE),
    ('AMA201', 'Advanced Male Traditional Open Barehand', 'A', 'M', FALSE),
    ('AFA221', 'Advanced Female Traditional Short Weapon', 'A', 'F', FALSE),
    ('AMA221', 'Advanced Male Traditional Short Weapon', 'A', 'M', FALSE),
    ('AFA241', 'Advanced Female Traditional Long Weapon', 'A', 'F', FALSE),
    ('AMA241', 'Advanced Male Traditional Long Weapon', 'A', 'M', FALSE),
    ('AFA281', 'Advanced Female Traditional Soft Weapon', 'A', 'F', FALSE),
    ('AMA281', 'Advanced Male Traditional Soft Weapon', 'A', 'M', FALSE),
    ('AFA181', 'Advanced Female Other Weapon', 'A', 'F', FALSE),
    ('AMA181', 'Advanced Male Other Weapon', 'A', 'M', FALSE),
    ('AFA321', 'Advanced Female Taiji 24', 'A', 'F', FALSE),
    ('AMA321', 'Advanced Male Taiji 24', 'A', 'M', FALSE),
    ('AFA322', 'Advanced Female Yang', 'A', 'F', FALSE),
    ('AMA322', 'Advanced Male Yang', 'A', 'M', FALSE),
    ('AFA323', 'Advanced Female Chen', 'A', 'F', FALSE),
    ('AMA323', 'Advanced Male Chen', 'A', 'M', FALSE),
    ('AFA301', 'Advanced Female 42 Fist', 'A', 'F', FALSE),
    ('AMA301', 'Advanced Male 42 Fist', 'A', 'M', FALSE),
    ('AFA302', 'Advanced Female 42 Sword', 'A', 'F', FALSE),
    ('AMA302', 'Advanced Male 42 Sword', 'A', 'M', FALSE),
    ('AFA341', 'Advanced Female Taiji Weapon', 'A', 'F', FALSE),
    ('AMA341', 'Advanced Male Taiji Weapon', 'A', 'M', FALSE),
    ('AFA361', 'Advanced Female Internal Open Barehand', 'A', 'F', FALSE),
    ('AMA361', 'Advanced Male Internal Open Barehand', 'A', 'M', FALSE),
    ('AFA381', 'Advanced Female Internal Open Weapon', 'A', 'F', FALSE),
    ('AMA381', 'Advanced Male Internal Open Weapon', 'A', 'M', FALSE),
    ('IFA101', 'Intermediate Female Longfist', 'I', 'F', FALSE),
    ('IMA101', 'Intermediate Male Longfist', 'I', 'M', FALSE),
    ('IFA102', 'Intermediate Female Southern Fist', 'I', 'F', FALSE),
    ('IMA102', 'Intermediate Male Southern Fist', 'I', 'M', FALSE),
    ('IFA121', 'Intermediate Female Straightsword', 'I', 'F', FALSE),
    ('IMA121', 'Intermediate Male Straightsword', 'I', 'M', FALSE),
    ('IFA122', 'Intermediate Female Broadsword', 'I', 'F', FALSE),
    ('IMA122', 'Intermediate Male Broadsword', 'I', 'M', FALSE),
    ('IFA123', 'Intermediate Female Southern Broadsword', 'I', 'F', FALSE),
    ('IMA123', 'Intermediate Male Southern Broadsword', 'I', 'M', FALSE),
    ('IFA141', 'Intermediate Female Spear', 'I', 'F', FALSE),
    ('IMA141', 'Intermediate Male Spear', 'I', 'M', FALSE),
    ('IFA142', 'Intermediate Female Staff', 'I', 'F', FALSE),
    ('IMA142', 'Intermediate Male Staff', 'I', 'M', FALSE),
    ('IFA143', 'Intermediate Female Southern Staff', 'I', 'F', FALSE),
    ('IMA143', 'Intermediate Male Southern Staff', 'I', 'M', FALSE),
    ('IMF201', 'Intermediate Female Traditional Open Barehand', 'I', 'F', FALSE),
    ('IMA201', 'Intermediate Male Traditional Open Barehand', 'I', 'M', FALSE),
    ('IFA221', 'Intermediate Female Traditional Short Weapon', 'I', 'F', FALSE),
    ('IMA221', 'Intermediate Male Traditional Short Weapon', 'I', 'M', FALSE),
    ('IFA241', 'Intermediate Female Traditional Long Weapon', 'I', 'F', FALSE),
    ('IMA241', 'Intermediate Male Traditional Long Weapon', 'I', 'M', FALSE),
    ('IFA281', 'Intermediate Female Traditional Soft Weapon', 'I', 'F', FALSE),
    ('IMA281', 'Intermediate Male Traditional Soft Weapon', 'I', 'M', FALSE),
    ('IFA181', 'Intermediate Female Other Weapon', 'I', 'F', FALSE),
    ('IMA181', 'Intermediate Male Other Weapon', 'I', 'M', FALSE),
    ('IFA321', 'Intermediate Female Taiji 24', 'I', 'F', FALSE),
    ('IMA321', 'Intermediate Male Taiji 24', 'I', 'M', FALSE),
    ('IFA322', 'Intermediate Female Yang', 'I', 'F', FALSE),
    ('IMA322', 'Intermediate Male Yang', 'I', 'M', FALSE),
    ('IFA323', 'Intermediate Female Chen', 'I', 'F', FALSE),
    ('IMA323', 'Intermediate Male Chen', 'I', 'M', FALSE),
    ('IFA301', 'Intermediate Female 42 Fist', 'I', 'F', FALSE),
    ('IMA301', 'Intermediate Male 42 Fist', 'I', 'M', FALSE),
    ('IFA302', 'Intermediate Female 42 Sword', 'I', 'F', FALSE),
    ('IMA302', 'Intermediate Male 42 Sword', 'I', 'M', FALSE),
    ('IFA341', 'Intermediate Female Taiji Weapon', 'I', 'F', FALSE),
    ('IMA341', 'Intermediate Male Taiji Weapon', 'I', 'M', FALSE),
    ('IFA361', 'Intermediate Female Internal Open Barehand', 'I', 'F', FALSE),
    ('IMA361', 'Intermediate Male Internal Open Barehand', 'I', 'M', FALSE),
    ('IFA381', 'Intermediate Female Internal Open Weapon', 'I', 'F', FALSE),
    ('IMA381', 'Intermediate Male Internal Open Weapon', 'I', 'M', FALSE),
    ('BFA101', 'Beginner Female Longfist', 'B', 'F', FALSE),
    ('BMA101', 'Beginner Male Longfist', 'B', 'M', FALSE),
    ('BFA102', 'Beginner Female Southern Fist', 'B', 'F', FALSE),
    ('BMA102', 'Beginner Male Southern Fist', 'B', 'M', FALSE),
    ('BFA121', 'Beginner Female Straightsword', 'B', 'F', FALSE),
    ('BMA121', 'Beginner Male Straightsword', 'B', 'M', FALSE),
    ('BFA122', 'Beginner Female Broadsword', 'B', 'F', FALSE),
    ('BMA122', 'Beginner Male Broadsword', 'B', 'M', FALSE),
    ('BFA123', 'Beginner Female Southern Broadsword', 'B', 'F', FALSE),
    ('BMA123', 'Beginner Male Southern Broadsword', 'B', 'M', FALSE),
    ('BFA141', 'Beginner Female Spear', 'B', 'F', FALSE),
    ('BMA141', 'Beginner Male Spear', 'B', 'M', FALSE),
    ('BFA142', 'Beginner Female Staff', 'B', 'F', FALSE),
    ('BMA142', 'Beginner Male Staff', 'B', 'M', FALSE),
    ('BFA143', 'Beginner Female Southern Staff', 'B', 'F', FALSE),
    ('BMA143', 'Beginner Male Southern Staff', 'B', 'M', FALSE),
    ('BMF201', 'Beginner Female Traditional Open Barehand', 'B', 'F', FALSE),
    ('BMA201', 'Beginner Male Traditional Open Barehand', 'B', 'M', FALSE),
    ('BFA221', 'Beginner Female Traditional Short Weapon', 'B', 'F', FALSE),
    ('BMA221', 'Beginner Male Traditional Short Weapon', 'B', 'M', FALSE),
    ('BFA241', 'Beginner Female Traditional Long Weapon', 'B', 'F', FALSE),
    ('BMA241', 'Beginner Male Traditional Long Weapon', 'B', 'M', FALSE),
    ('BFA281', 'Beginner Female Traditional Soft Weapon', 'B', 'F', FALSE),
    ('BMA281', 'Beginner Male Traditional Soft Weapon', 'B', 'M', FALSE),
    ('BFA181', 'Beginner Female Other Weapon', 'B', 'F', FALSE),
    ('BMA181', 'Beginner Male Other Weapon', 'B', 'M', FALSE),
    ('BFA321', 'Beginner Female Taiji 24', 'B', 'F', FALSE),
    ('BMA321', 'Beginner Male Taiji 24', 'B', 'M', FALSE),
    ('BFA322', 'Beginner Female Yang', 'B', 'F', FALSE),
    ('BMA322', 'Beginner Male Yang', 'B', 'M', FALSE),
    ('BFA323', 'Beginner Female Chen', 'B', 'F', FALSE),
    ('BMA323', 'Beginner Male Chen', 'B', 'M', FALSE),
    ('BFA301', 'Beginner Female 42 Fist', 'B', 'F', FALSE),
    ('BMA301', 'Beginner Male 42 Fist', 'B', 'M', FALSE),
    ('BFA302', 'Beginner Female 42 Sword', 'B', 'F', FALSE),
    ('BMA302', 'Beginner Male 42 Sword', 'B', 'M', FALSE),
    ('BFA341', 'Beginner Female Taiji Weapon', 'B', 'F', FALSE),
    ('BMA341', 'Beginner Male Taiji Weapon', 'B', 'M', FALSE),
    ('BFA361', 'Beginner Female Internal Open Barehand', 'B', 'F', FALSE),
    ('BMA361', 'Beginner Male Internal Open Barehand', 'B', 'M', FALSE),
    ('BFA381', 'Beginner Female Internal Open Weapon', 'B', 'F', FALSE),
    ('BMA381', 'Beginner Male Internal Open Weapon', 'B', 'M', FALSE);