# Generated by Django 6.0.2 on 2026-03-04 23:38

import collegiates_app.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_user', models.CharField(max_length=255, unique=True)),
                ('admin_password', models.BinaryField()),
            ],
            options={
                'db_table': 'admin_account',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('blog_content', models.TextField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('gender_category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_nandu', models.BooleanField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('student_status', models.CharField(choices=[('1', 'Full/Part-Time Undergraduate'), ('2', 'Full-Time Graduate/Professional School'), ('3', 'Fall/Winter Graduates of Current Academic Year'), ('4', 'Non-Enrolled Student'), ('5', '1yr Alumni'), ('6', 'Part-Time Graduate/Professional School'), ('7', 'International Student')], max_length=1)),
                ('first_comp', models.IntegerField()),
                ('skill_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('grad_date', models.DateField()),
                ('is_competing', models.BooleanField(default=False)),
                ('has_paid', models.BooleanField(default=False)),
                ('proof_of_reg', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegiates_app.college')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', collegiates_app.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Groupset',
            fields=[
                ('groupset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comp_year', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('member_2', models.ForeignKey(blank=True, db_column='member_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_2', to=settings.AUTH_USER_MODEL)),
                ('member_3', models.ForeignKey(blank=True, db_column='member_3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_3', to=settings.AUTH_USER_MODEL)),
                ('member_4', models.ForeignKey(blank=True, db_column='member_4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_4', to=settings.AUTH_USER_MODEL)),
                ('member_5', models.ForeignKey(blank=True, db_column='member_5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_5', to=settings.AUTH_USER_MODEL)),
                ('member_6', models.ForeignKey(blank=True, db_column='member_6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_6', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.college')),
                ('team_leader', models.ForeignKey(blank=True, db_column='team_leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groupsets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groupset',
            },
        ),
        migrations.CreateModel(
            name='Nandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_year', models.DateField()),
                ('nandu_str', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(db_column='event_code', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.event')),
            ],
            options={
                'db_table': 'nandu',
                'unique_together': {('competitor', 'comp_year', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_year', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(db_column='event_code', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.event')),
            ],
            options={
                'db_table': 'registration',
                'unique_together': {('competitor', 'comp_year', 'event')},
            },
        ),
    ]
