# Generated by Django 5.2.6 on 2026-02-06 00:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admin_user', models.CharField(max_length=255, unique=True)),
                ('admin_password', models.BinaryField()),
            ],
            options={
                'db_table': 'admin_account',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('blog_content', models.TextField()),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'colleges',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=255, unique=True)),
                ('event_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('gender_category', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_nandu', models.BooleanField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.BinaryField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('student_type', models.CharField(choices=[('U', 'Undergraduate'), ('G', 'Graduate')], max_length=1)),
                ('first_comp', models.DateField()),
                ('undergrad_year', models.IntegerField(blank=True, null=True)),
                ('skill_level', models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], max_length=1)),
                ('grad_date', models.DateField()),
                ('is_competing', models.BooleanField(default=False)),
                ('has_paid', models.BooleanField(default=False)),
                ('proof_of_reg', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, db_column='school_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='collegiates_app.college')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Groupset',
            fields=[
                ('groupset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comp_year', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(db_column='school_id', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.college')),
                ('member_2', models.ForeignKey(blank=True, db_column='member_2', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_2', to='collegiates_app.user')),
                ('member_3', models.ForeignKey(blank=True, db_column='member_3', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_3', to='collegiates_app.user')),
                ('member_4', models.ForeignKey(blank=True, db_column='member_4', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_4', to='collegiates_app.user')),
                ('member_5', models.ForeignKey(blank=True, db_column='member_5', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_5', to='collegiates_app.user')),
                ('member_6', models.ForeignKey(blank=True, db_column='member_6', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groupset_member_6', to='collegiates_app.user')),
                ('team_leader', models.ForeignKey(blank=True, db_column='team_leader', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groupsets', to='collegiates_app.user')),
            ],
            options={
                'db_table': 'groupset',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_year', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_code', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.event')),
                ('competitor', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.user')),
            ],
            options={
                'db_table': 'registration',
                'unique_together': {('competitor', 'comp_year', 'event')},
            },
        ),
        migrations.CreateModel(
            name='Nandu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_year', models.DateField()),
                ('nandu_str', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(db_column='event_code', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.event')),
                ('competitor', models.ForeignKey(db_column='competitor_id', on_delete=django.db.models.deletion.CASCADE, to='collegiates_app.user')),
            ],
            options={
                'db_table': 'nandu',
                'unique_together': {('competitor', 'comp_year', 'event')},
            },
        ),
    ]
