# Generated by Django 6.0.2 on 2026-03-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegiates_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
