# Generated by Django 6.0.2 on 2026-03-05 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegiates_app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_status',
            new_name='student_type',
        ),
    ]
