// Reference college list, originally mirroring collegiates_backend/sql_files/metadata_queries.sql.
// Names have since been normalized, so entries no longer match that file verbatim.
export const colleges: string[] = [
  "University of Maryland, College Park",
  "Columbia",
  "UC Berkeley",
  "Cornell",
  "Georgia Tech",
  "Harvard",
  "Northern Arizona University",
  "Ohio State University",
  "San Jose State University",
  "Stanford",
  "UC Irvine",
  "UCLA",
  "University of Houston",
  "University of Maryland, Baltimore County",
  "UNC Chapel Hill",
  "University of Oregon",
  "UT Austin",
  "University of Virginia",
  "University of Washington",
  "Virginia Tech",
  "Yale",
  "Wellesley College",
  "UC San Diego",
  "UC Davis",
  "USC",
  "Cal Poly Pomona",
  "UC Merced",
  "Cal State Fullerton",
  "Palmer College of Chiropractic West",
  "Santa Monica College",
  "East Los Angeles College",
  "UCSF",
  "UC Santa Cruz",
  "Pasadena City College",
  "Portland Community College",
  "UC Santa Barbara",
  "UPenn",
  "Berklee College of Music",
  "University of Maryland, Baltimore",
  "Santa Rosa Junior College",
  "Georgetown",
  "University of Nebraska at Kearney",
  "Pacific College of Health and Science",
  "UC Riverside",
  "University of Maryland Global Campus",
  "California College of the Arts",
  "ASU",
  "UH Maui College",
  "Leeward Community College",
  "Kapi'olani Community College",
  "University of Hawai'i at Manoa",
  "UH West O'ahu",
  "Carnegie Mellon",
  "Pitt",
  "VCU",
  "Point Park University",
  "MIT",
  "Bentley University",
  "Rutgers-New Brunswick",
  "UIUC",
  "Saint Peter's University",
  "College of Staten Island",
  "Seattle Central College",
  "San Francisco State University",
  "Bastyr University",
  "Central Washington University",
  "San Diego Miramar College",
  "Cal State Long Beach",
  "Stony Brook University",
  "NYU",
  "MICA",
  "Cosumnes River College",
  "West Coast University",
  "University of Oklahoma",
  "George Mason University",
  "Chapman University",
  "SUNY Empire",
  "UChicago",
  "University of Alaska Southeast",
  "Northeastern",
  "San Diego State",
  "Case Western",
  "Berkeley City College",
  "NJIT",
  "Boston University",
  "Juilliard",
];
