// Reference college list, mirroring collegiates_backend/sql_files/metadata_queries.sql.
export const colleges: string[] = [
  "U Maryland: College Park",
  "Columbia U",
  "UC Berkeley",
  "Cornell U",
  "Georgia Tech",
  "Harvard U",
  "Northern Arizona U",
  "Ohio State U",
  "San Jose State U",
  "Stanford U",
  "UC Irvine",
  "UC Los Angeles",
  "U Houston",
  "U Maryland: Baltimore County",
  "U North Carolina",
  "U Oregon",
  "U Texas",
  "U Virginia",
  "U Washington",
  "Virginia Tech",
  "Yale U",
  "Wellesley U",
  "UC San Diego",
  "UC Davis",
  "U Southern California",
  "Cal Poly Pomona",
  "UC Merced",
  "California State U, Fullerton",
  "Palmer College of Chiropractic West",
  "Santa Monica College",
  "East Lost Angeles College",
  "UC San Francisco",
  "UC Santa Cruz",
  "Pasadena City College",
  "Portland Community College",
  "UC Santa Barbara",
  "U Pennsylvania",
  "Berklee College of Music",
  "U Maryland: Baltimore",
  "Santa Rosa Junior College",
  "Georgetown University",
  "U Nebraska, Kearney",
  "Pacific College of Oriental Medicine",
  "UC Riverside",
  "U Maryland: University College",
  "California College of the Arts",
  "Arizona State U",
  "U Hawaii - Maui College",
  "Leeward Community College",
  "Kapi'olani Community College",
  "U Hawaii - Manoa",
  "U Hawaii - West Oahu",
  "Carnegie Mellon U",
  "U Pittsburgh",
  "Virginia Commonwealth U",
  "Point Park University",
  "Massachusetts Institute of Technology",
  "Bentley University",
  "Rutgers U - New Brunswick",
  "U Illinois Urbana-Champaign",
  "Saint Peter's University",
  "College of Staten Island",
  "Seattle Central College",
  "San Francisco State U",
  "Bastyr U",
  "Central Washington U",
  "San Diego Miramar College",
  "California State U, Long Beach",
  "SUNY Stony Brook ",
  "New York U",
  "Maryland Institute College of Art",
  "Cosumnes River College",
  "West Coast University",
  "U Oklahoma",
  "Univ of Oklahoma",
  "George Mason U",
  "Chapman Univ",
  "SUNY Empire State College",
  "U Chicago",
  "University of Alaska Southeast",
  "Northeastern University",
  "San Diego State University",
  "Case Western Reserve University",
  "Berkeley City College",
  "New Jersey Institute of Technology",
  "Boston University",
  "The Juilliard School",
];
